package com.scalaforge.cli

import java.nio.charset.StandardCharsets
import java.nio.file.{Files, Path, Paths}

object CliAppScaffolder {
  final case class Result(projectRoot: Path, plannedFiles: List[Path], dryRun: Boolean)

  private val NamePattern = "^[A-Za-z][A-Za-z0-9_-]*$".r

  def scaffold(
      projectName: String,
      scalaVersion: String,
      overwrite: Boolean,
      dryRun: Boolean,
      baseDir: Path = Paths.get(".")
  ): Either[String, Result] = {
    if (!NamePattern.matches(projectName)) {
      Left("Project name must match ^[A-Za-z][A-Za-z0-9_-]*$")
    } else {
      val root = baseDir.toAbsolutePath.normalize().resolve(projectName)
      val pkg = packageName(projectName)
      val pkgPath = pkg.replace('.', '/')

      val files = List(
        "build.sbt" ->
          s"""ThisBuild / organization := "com.example"
             |ThisBuild / scalaVersion := "$scalaVersion"
             |ThisBuild / version := "0.1.0-SNAPSHOT"
             |
             |lazy val root = project
             |  .in(file("."))
             |  .settings(
             |    name := "$projectName",
             |    Compile / mainClass := Some("$pkg.Main"),
             |    libraryDependencies += "org.scalatest" %% "scalatest" % "3.2.19" % Test
             |  )
             |""".stripMargin,
        "project/build.properties" ->
          "sbt.version=1.10.2\n",
        "project/plugins.sbt" ->
          "addSbtPlugin(\"org.scalameta\" % \"sbt-scalafmt\" % \"2.5.2\")\n",
        s"src/main/scala/$pkgPath/Main.scala" ->
          s"""package $pkg
             |
             |object Main {
             |  def main(args: Array[String]): Unit =
             |    println("Hello from $projectName")
             |}
             |""".stripMargin,
        s"src/test/scala/$pkgPath/MainSpec.scala" ->
          s"""package $pkg
             |
             |import org.scalatest.funsuite.AnyFunSuite
             |
             |class MainSpec extends AnyFunSuite {
             |  test("project scaffold compiles") {
             |    assert(1 + 1 == 2)
             |  }
             |}
             |""".stripMargin,
        ".gitignore" ->
          """target/
            |project/target/
            |.bsp/
            |.metals/
            |.bloop/
            |""".stripMargin,
        "README.md" ->
          s"""# $projectName
             |
             |Generated by Scala Forge (`cli-app` template).
             |
             |## Run
             |```bash
             |sbt run
             |```
             |
             |## Test
             |```bash
             |sbt test
             |```
             |""".stripMargin
      )

      val targets = files.map { case (relative, content) =>
        (root.resolve(relative), content)
      }

      val conflicts = targets.collect { case (path, _) if Files.exists(path) && !overwrite => path }
      if (conflicts.nonEmpty) {
        val listed = conflicts.take(5).map(_.toString).mkString("\n  - ", "\n  - ", "")
        Left(
          s"""Refusing to overwrite existing files.
             |Use --overwrite to replace them.
             |Conflicts:$listed""".stripMargin
        )
      } else {
        if (!dryRun) {
          targets.foreach { case (path, content) =>
            val parent = path.getParent
            if (parent != null) {
              Files.createDirectories(parent)
            }
            Files.write(path, content.getBytes(StandardCharsets.UTF_8))
          }
        }
        Right(Result(root, targets.map(_._1), dryRun))
      }
    }
  }

  private def packageName(projectName: String): String = {
    val tokens = projectName
      .toLowerCase
      .split("[^a-z0-9]+")
      .toList
      .filter(_.nonEmpty)

    ("com" :: "example" :: tokens).mkString(".")
  }
}
